spring.application.name=BackEndServlet
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookShopDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
BackEndServlet.api.key =k0KNY+nrt5Z2nfuLe1M003S+hGIZSHmbfR4DqVWLBMVuNcXkf70dRxTvyuWFFrA7
